# -*- coding: utf-8 -*-
"""
EAI日志监听服务 - 数据库操作模块
负责ACC Oracle数据库的连接和数据插入
"""

import logging
from typing import List, Optional, Set
from datetime import datetime
from contextlib import contextmanager
import threading

import cx_Oracle

from config import ACC_DATABASE, get_dsn
from log_parser import ReportRecord

logger = logging.getLogger(__name__)


class DBHandler:
    """ACC数据库操作类"""

    # 目标表名
    TABLE_NAME = 'ACC_ERP_REPORT_SUCCESS'

    # 建表DDL（如果表不存在）
    # 注意：增加了SOURCE_BILL_NO字段用于追溯源单号
    CREATE_TABLE_DDL = """
    CREATE TABLE ACC_ERP_REPORT_SUCCESS (
        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        SCHB_NUMBER VARCHAR2(100) NOT NULL,
        SOURCE_BILL_NO VARCHAR2(100),
        QTY NUMBER(18,4),
        PRODUCT_CODE VARCHAR2(100),
        PROCESS_CODE VARCHAR2(100),
        REPORT_TIME DATE,
        WORKER_CODE VARCHAR2(100),
        RAW_REQUEST CLOB,
        RAW_RESPONSE CLOB,
        CREATE_TIME DATE DEFAULT SYSDATE,
        CONSTRAINT UK_SCHB_NUMBER UNIQUE (SCHB_NUMBER)
    )
    """

    # 新增字段DDL（用于升级已有表）
    ADD_SOURCE_BILL_NO_DDL = """
    ALTER TABLE ACC_ERP_REPORT_SUCCESS ADD SOURCE_BILL_NO VARCHAR2(100)
    """

    # 错误信息字段DDL
    ADD_ERROR_MESSAGE_DDL = """
    ALTER TABLE ACC_ERP_REPORT_SUCCESS ADD ERROR_MESSAGE VARCHAR2(2000)
    """

    # 成功标志字段DDL
    ADD_IS_SUCCESS_DDL = """
    ALTER TABLE ACC_ERP_REPORT_SUCCESS ADD IS_SUCCESS NUMBER(1) DEFAULT 1
    """

    def __init__(self, schema_name: str):
        """
        初始化数据库处理器

        Args:
            schema_name: 模式名称 (dpepp1, smt2, dpeps1)
        """
        self.schema_name = schema_name
        self._schema_config = ACC_DATABASE['schemas'].get(schema_name)
        if not self._schema_config:
            raise ValueError(f"Unknown schema: {schema_name}")

        self._dsn = get_dsn(schema_name)
        self._pool = None
        self._lock = threading.Lock()
        self._inserted_schb_numbers: Set[str] = set()  # 内存缓存已插入的工单号

    def connect(self):
        """建立数据库连接池"""
        try:
            self._pool = cx_Oracle.SessionPool(
                user=self._schema_config['user'],
                password=self._schema_config['password'],
                dsn=self._dsn,
                min=1,
                max=5,
                increment=1,
                encoding='UTF-8'
            )
            logger.info(f"数据库连接池创建成功: {self.schema_name}")

            # 确保表存在
            self._ensure_table_exists()

            # 加载已存在的工单号到内存缓存
            self._load_existing_schb_numbers()

        except cx_Oracle.Error as e:
            logger.error(f"数据库连接失败: {e}")
            raise

    def disconnect(self):
        """关闭数据库连接池"""
        if self._pool:
            self._pool.close()
            self._pool = None
            logger.info(f"数据库连接池已关闭: {self.schema_name}")

    @contextmanager
    def get_connection(self):
        """获取数据库连接的上下文管理器"""
        conn = None
        try:
            conn = self._pool.acquire()
            yield conn
        finally:
            if conn:
                self._pool.release(conn)

    def _ensure_table_exists(self):
        """确保目标表存在，并检查字段是否完整"""
        try:
            with self.get_connection() as conn:
                cursor = conn.cursor()

                # 检查表是否存在
                cursor.execute("""
                    SELECT COUNT(*) FROM user_tables WHERE table_name = :table_name
                """, {'table_name': self.TABLE_NAME})

                if cursor.fetchone()[0] == 0:
                    # 创建表
                    logger.info(f"创建表: {self.TABLE_NAME}")
                    cursor.execute(self.CREATE_TABLE_DDL)
                    conn.commit()
                    logger.info(f"表创建成功: {self.TABLE_NAME}")
                else:
                    logger.info(f"表已存在: {self.TABLE_NAME}")
                    # 检查SOURCE_BILL_NO字段是否存在
                    cursor.execute("""
                        SELECT COUNT(*) FROM user_tab_columns
                        WHERE table_name = :table_name AND column_name = 'SOURCE_BILL_NO'
                    """, {'table_name': self.TABLE_NAME})

                    if cursor.fetchone()[0] == 0:
                        # 添加新字段
                        logger.info(f"添加字段: SOURCE_BILL_NO")
                        cursor.execute(self.ADD_SOURCE_BILL_NO_DDL)
                        conn.commit()
                        logger.info(f"字段添加成功: SOURCE_BILL_NO")

                    # 检查ERROR_MESSAGE字段是否存在
                    cursor.execute("""
                        SELECT COUNT(*) FROM user_tab_columns
                        WHERE table_name = :table_name AND column_name = 'ERROR_MESSAGE'
                    """, {'table_name': self.TABLE_NAME})

                    if cursor.fetchone()[0] == 0:
                        logger.info(f"添加字段: ERROR_MESSAGE")
                        cursor.execute(self.ADD_ERROR_MESSAGE_DDL)
                        conn.commit()
                        logger.info(f"字段添加成功: ERROR_MESSAGE")

                    # 检查IS_SUCCESS字段是否存在
                    cursor.execute("""
                        SELECT COUNT(*) FROM user_tab_columns
                        WHERE table_name = :table_name AND column_name = 'IS_SUCCESS'
                    """, {'table_name': self.TABLE_NAME})

                    if cursor.fetchone()[0] == 0:
                        logger.info(f"添加字段: IS_SUCCESS")
                        cursor.execute(self.ADD_IS_SUCCESS_DDL)
                        conn.commit()
                        logger.info(f"字段添加成功: IS_SUCCESS")

        except cx_Oracle.Error as e:
            logger.error(f"检查/创建表失败: {e}")
            # 表可能已存在，不抛出异常

    def _load_existing_schb_numbers(self):
        """加载已存在的工单号到内存缓存"""
        try:
            with self.get_connection() as conn:
                cursor = conn.cursor()
                cursor.execute(f"SELECT SCHB_NUMBER FROM {self.TABLE_NAME}")

                with self._lock:
                    self._inserted_schb_numbers = {row[0] for row in cursor.fetchall()}

                logger.info(f"已加载 {len(self._inserted_schb_numbers)} 个已存在的工单号")

        except cx_Oracle.Error as e:
            logger.warning(f"加载已存在工单号失败: {e}")

    def is_duplicate(self, schb_number: str) -> bool:
        """
        检查工单号是否重复

        Args:
            schb_number: 工单号

        Returns:
            True表示重复，False表示不重复
        """
        with self._lock:
            return schb_number in self._inserted_schb_numbers

    def is_error_duplicate(self, wono: str, packid: str, error_message: str) -> bool:
        """
        检查失败记录是否已存在（基于WONO + PACKID + ERROR_MESSAGE组合）

        用于EAI重试场景下的错误日志去重，避免同一错误被重复记录

        Args:
            wono: 工单号（源单号）
            packid: 批次号
            error_message: 错误信息

        Returns:
            True表示已存在相同错误记录，False表示不存在
        """
        if not wono or not error_message:
            return False

        try:
            with self.get_connection() as conn:
                cursor = conn.cursor()

                # 截断错误信息用于比较（与插入时保持一致）
                error_msg_truncated = error_message[:2000] if error_message else ''

                cursor.execute(f"""
                    SELECT COUNT(*) FROM {self.TABLE_NAME}
                    WHERE WONO = :wono
                    AND NVL(PACKID, '') = NVL(:packid, '')
                    AND ERROR_MESSAGE = :error_message
                    AND IS_SUCCESS = 0
                """, {
                    'wono': wono,
                    'packid': packid or '',
                    'error_message': error_msg_truncated
                })

                count = cursor.fetchone()[0]
                return count > 0

        except cx_Oracle.Error as e:
            logger.warning(f"检查错误记录重复失败: {e}")
            return False  # 检查失败时不阻止插入

    def insert_record(self, record: ReportRecord) -> bool:
        """
        插入单条报工记录

        Args:
            record: 报工记录

        Returns:
            插入成功返回True，否则返回False
        """
        # 先检查内存缓存（仅对成功记录检查重复）
        if record.is_success and self.is_duplicate(record.schb_number):
            logger.debug(f"工单号重复，跳过: {record.schb_number}")
            return False

        # 对失败记录检查错误去重（基于WONO + PACKID + ERROR_MESSAGE）
        if not record.is_success:
            if self.is_error_duplicate(
                record.source_bill_no or 'UNKNOWN',
                record.lot_number or '',
                record.error_message or ''
            ):
                logger.debug(f"错误记录重复，跳过: WONO={record.source_bill_no}, PACKID={record.lot_number}")
                return False

        try:
            with self.get_connection() as conn:
                cursor = conn.cursor()

                # 使用MERGE实现UPSERT（如果存在则跳过）
                # 表结构：ID(序列), WONO(源单号), PACKID(批次), PARTNO(产品), CNT(数量), LINE(产线)
                # WONO = source_bill_no (NOT NULL)
                # 新增字段：IS_SUCCESS(成功标志), ERROR_MESSAGE(错误信息)
                sql = f"""
                MERGE INTO {self.TABLE_NAME} t
                USING (SELECT :schb_number AS SCHB_NUMBER FROM DUAL) s
                ON (t.SCHB_NUMBER = s.SCHB_NUMBER)
                WHEN NOT MATCHED THEN
                INSERT (ID, WONO, PACKID, PARTNO, CNT, LINE, SCHB_NUMBER, SOURCE_BILL_NO, REPORT_TIME, IS_SUCCESS, ERROR_MESSAGE)
                VALUES (ACC_ERP_REPT_SUCC_SEQ.NEXTVAL, :wono, :packid, :partno, :cnt, :line, :schb_number, :source_bill_no, :report_time, :is_success, :error_message)
                """

                # 截断错误信息以适应字段长度
                error_message = record.error_message[:2000] if record.error_message else ''

                cursor.execute(sql, {
                    'schb_number': record.schb_number,
                    'wono': record.source_bill_no or 'UNKNOWN',
                    'packid': record.lot_number or '',
                    'source_bill_no': record.source_bill_no,
                    'cnt': record.qty,
                    'partno': record.product_code or 'UNKNOWN',
                    'line': record.line or '',
                    'report_time': record.report_time,
                    'is_success': 1 if record.is_success else 0,
                    'error_message': error_message
                })

                rows_affected = cursor.rowcount
                conn.commit()

                if rows_affected > 0:
                    # 更新内存缓存（仅成功记录）
                    if record.is_success:
                        with self._lock:
                            self._inserted_schb_numbers.add(record.schb_number)
                    status = '成功' if record.is_success else '失败'
                    logger.info(f"插入{status}记录: {record.schb_number}")
                    return True
                else:
                    logger.debug(f"记录已存在: {record.schb_number}")
                    return False

        except cx_Oracle.Error as e:
            logger.error(f"插入记录失败: {e}, 工单号: {record.schb_number}")
            return False

    def insert_records_batch(self, records: List[ReportRecord]) -> int:
        """
        批量插入报工记录

        Args:
            records: 报工记录列表

        Returns:
            成功插入的记录数
        """
        if not records:
            return 0

        # 过滤重复的成功记录（基于内存缓存）
        new_records = [r for r in records if not r.is_success or not self.is_duplicate(r.schb_number)]
        if not new_records:
            return 0

        success_count = 0
        skipped_count = 0
        try:
            with self.get_connection() as conn:
                cursor = conn.cursor()

                for record in new_records:
                    try:
                        # 对失败记录检查错误去重（基于WONO + PACKID + ERROR_MESSAGE）
                        if not record.is_success:
                            if self.is_error_duplicate(
                                record.source_bill_no or 'UNKNOWN',
                                record.lot_number or '',
                                record.error_message or ''
                            ):
                                logger.debug(f"错误记录重复，跳过: WONO={record.source_bill_no}, PACKID={record.lot_number}")
                                skipped_count += 1
                                continue

                        # 表结构：ID(序列), WONO(源单号), PACKID(批次), PARTNO(产品), CNT(数量), LINE(产线)
                        # 新增字段：IS_SUCCESS(成功标志), ERROR_MESSAGE(错误信息)
                        sql = f"""
                        MERGE INTO {self.TABLE_NAME} t
                        USING (SELECT :schb_number AS SCHB_NUMBER FROM DUAL) s
                        ON (t.SCHB_NUMBER = s.SCHB_NUMBER)
                        WHEN NOT MATCHED THEN
                        INSERT (ID, WONO, PACKID, PARTNO, CNT, LINE, SCHB_NUMBER, SOURCE_BILL_NO, REPORT_TIME, IS_SUCCESS, ERROR_MESSAGE)
                        VALUES (ACC_ERP_REPT_SUCC_SEQ.NEXTVAL, :wono, :packid, :partno, :cnt, :line, :schb_number, :source_bill_no, :report_time, :is_success, :error_message)
                        """

                        # 截断错误信息以适应字段长度
                        error_message = record.error_message[:2000] if record.error_message else ''

                        cursor.execute(sql, {
                            'schb_number': record.schb_number,
                            'wono': record.source_bill_no or 'UNKNOWN',
                            'packid': record.lot_number or '',
                            'source_bill_no': record.source_bill_no,
                            'cnt': record.qty,
                            'partno': record.product_code or 'UNKNOWN',
                            'line': record.line or '',
                            'report_time': record.report_time,
                            'is_success': 1 if record.is_success else 0,
                            'error_message': error_message
                        })

                        if cursor.rowcount > 0:
                            success_count += 1
                            # 仅成功记录加入缓存
                            if record.is_success:
                                with self._lock:
                                    self._inserted_schb_numbers.add(record.schb_number)

                    except cx_Oracle.Error as e:
                        logger.warning(f"批量插入单条失败: {e}, 工单号: {record.schb_number}")

                conn.commit()

        except cx_Oracle.Error as e:
            logger.error(f"批量插入失败: {e}")

        if skipped_count > 0:
            logger.info(f"批量插入完成: {success_count}/{len(new_records)} 条，跳过重复错误记录: {skipped_count} 条")
        else:
            logger.info(f"批量插入完成: {success_count}/{len(new_records)} 条")
        return success_count

    def get_record_count(self) -> int:
        """获取表中的记录总数"""
        try:
            with self.get_connection() as conn:
                cursor = conn.cursor()
                cursor.execute(f"SELECT COUNT(*) FROM {self.TABLE_NAME}")
                return cursor.fetchone()[0]
        except cx_Oracle.Error as e:
            logger.error(f"查询记录数失败: {e}")
            return -1

    def get_recent_records(self, limit: int = 10) -> List[dict]:
        """获取最近的记录"""
        try:
            with self.get_connection() as conn:
                cursor = conn.cursor()
                # 使用实际表结构的列名
                cursor.execute(f"""
                    SELECT SCHB_NUMBER, CNT, PARTNO, REPORT_TIME, CREATETIME
                    FROM {self.TABLE_NAME}
                    ORDER BY CREATETIME DESC
                    FETCH FIRST :limit ROWS ONLY
                """, {'limit': limit})

                columns = ['schb_number', 'qty', 'product_code', 'report_time', 'create_time']
                return [dict(zip(columns, row)) for row in cursor.fetchall()]

        except cx_Oracle.Error as e:
            logger.error(f"查询最近记录失败: {e}")
            return []


class DBHandlerManager:
    """数据库处理器管理类"""

    def __init__(self):
        self._handlers: dict[str, DBHandler] = {}

    def get_handler(self, schema_name: str) -> DBHandler:
        """
        获取或创建数据库处理器

        Args:
            schema_name: 模式名称

        Returns:
            DBHandler实例
        """
        if schema_name not in self._handlers:
            handler = DBHandler(schema_name)
            handler.connect()
            self._handlers[schema_name] = handler

        return self._handlers[schema_name]

    def close_all(self):
        """关闭所有数据库连接"""
        for handler in self._handlers.values():
            handler.disconnect()
        self._handlers.clear()
